name: "Email Notificationss"

on:
  push:
    branches: [ main ]

jobs:
  send-notification:
    name: Send Email Notification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Notification: Code Pushed to Main"
        body: "Code has been pushed to the main branch. Please review the changes."
        to: "zeal.amrish@gmail.com"
        from: "zeal.amrish@gmail.com"
